export const PROBLEM_TAGS = [
  'Array',
  'String',
  'Hash Table',
  'Dynamic Programming',
  'Math',
  'Sorting',
  'Greedy',
  'Depth-First Search',
  'Binary Search',
  'Database',
  'Matrix',
  'Tree',
  'Bit Manipulation',
  'Breadth-First Search',
  'Two Pointers',
  'Prefix Sum',
  'Heap (Priority Queue)',
  'Simulation',
  'Binary Tree',
  'Stack',
  'Graph',
  'Counting',
  'Sliding Window',
  'Design',
  'Enumeration',
  'Backtracking',
  'Union Find',
  'Linked List',
  'Number Theory',
  'Ordered Set',
  'Monotonic Stack',
  'Segment Tree',
  'Trie',
  'Combinatorics',
  'Bitmask',
  'Queue',
  'Recursion',
  'Divide and Conquer',
  'Binary Indexed Tree',
  'Memoization',
  'Geometry',
  'Hash Function',
  'Binary Search Tree',
  'String Matching',
  'Topological Sort',
  'Shortest Path',
  'Rolling Hash',
  'Game Theory',
  'Interactive',
  'Data Stream',
  'Monotonic Queue',
  'Brainteaser',
  'Doubly-Linked List',
  'Randomized',
  'Merge Sort',
  'Counting Sort',
  'Iterator',
  'Concurrency',
  'Probability and Statistics',
  'Quickselect',
  'Suffix Array',
  'Line Sweep',
  'Minimum Spanning Tree',
  'Bucket Sort',
  'Shell',
  'Reservoir Sampling',
  'Strongly Connected Component',
  'Eulerian Circuit',
  'Radix Sort',
  'Rejection Sampling',
  'Biconnected Component',
  'Collapse',
];
